### ISSUE TITLE
Upgrade libwebrtc to M83

### ISSUE THREAD

**Issue by iNPUTmice** [iNPUTmice/Conversations#3767]
We should upgrade libwebrtc to M83 (We are currently on M81. There is no M82)

Release notes are here: https://groups.google.com/forum/#!topic/discuss-webrtc/EieMDYtQ9sg

**Comment by licaon-kter** [comment]
Are you aiming to improve the experience via the new degradation options?

**Comment by licaon-kter** [comment]
So did you build M83 locally?

I'm looking at this, to integrate it in F-Droid, but it's acting funny.

I had an old webrtc repo `master` _(M81 maybe)_ that I've just rsynced into the VM and it built ok.

But now, if in the VM I choose the actual branch via `git checkout branch-heads/4103` it starts tripping on its own files with errors _(Werror I believe)_ like:
* `ERROR at //webrtc.gni:997:27: Assignment had no effect.`
* (if I remove that line above) `ERROR at examples/BUILD.gn:104:33: Assignment had no effect`

And the solutions, according to the search engine results, are to _"use master"_ which is rather odd since I don't want to use master but the actual release branch.

Ref: https://groups.google.com/forum/#!msg/discuss-webrtc/Ozvbd0p7Q1Y/M4WN2cRKCwAJ
Ref: https://groups.google.com/forum/#!msg/discuss-webrtc/JR7fsoEuqw0/egT626FSAgAJ
Ref: https://chromiumdash.appspot.com/branches

**Comment by iNPUTmice** [comment]
Yes. I've just build M83. But I didn’t run it yet.

**Comment by licaon-kter** [comment]
Did you select the branch like I did or differently?

**Comment by licaon-kter** [comment]
Right, so it might look like this:
```
  - versionName: 2.8.6+fcr
    versionCode: 390
    commit: 2.8.6
    gradle:
      - conversationsFreeCompat
    prebuild:
      - sed -i -e '/ExtraTranslation/aabortOnError\ false' -e
        '/splits/,+5d' -e '/Variants.all/,+10d' build.gradle
      - pushd ~
      - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - export PATH=~/depot_tools:$PATH
      - mkdir webrtc
      - cd webrtc
      - fetch --nohooks webrtc_android
      - gclient sync
      - cd src
      - git checkout branch-heads/4103
      - cd ..
      - gclient sync -D
      - cd src
      - ./tools_webrtc/android/build_aar.py
      - popd
      - mkdir libs
      - cp ~/webrtc/src/libwebrtc.aar libs/libwebrtc-m81.aar
    ndk: r21b
```
...which builds fine.
